# Generated by Django 3.1.1 on 2020-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('module', models.CharField(max_length=100, verbose_name='مدل')),
                ('mony', models.IntegerField(verbose_name='مبلغ')),
                ('color', models.CharField(choices=[('w', 'سفید'), ('b', 'قهوه ای'), ('d', 'مشکی'), ('c', 'سایر رنگ ها')], max_length=1, verbose_name='رنگ')),
                ('image', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('info', models.TextField(verbose_name='اطلاعات بیشتر')),
            ],
            options={
                'verbose_name': 'مشخصات ساعت',
            },
        ),
    ]
