# Generated by Django 3.1.1 on 2020-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clock',
            options={'verbose_name': 'مشخصات ساعت', 'verbose_name_plural': 'مشخصات انواع ساعت ها'},
        ),
        migrations.AddField(
            model_name='clock',
            name='status',
            field=models.CharField(default='d', max_length=100),
        ),
    ]
