# Generated by Django 3.1.1 on 2020-09-17 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200913_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='سرتیتر')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='ادرس')),
                ('image', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('body', models.TextField(verbose_name='بدنه متن')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('p', 'منتشر'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
                ('athor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='ادرس')),
            ],
        ),
        migrations.DeleteModel(
            name='Clock',
        ),
    ]
